<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2018 phpjm.net All Rights Reserved.
*/
if (!defined("EBBCAEBCBBBC")){define("EBBCAEBCBBBC", __FILE__);global $ƒ,$‡Š,$„’™,$Žƒ–Š,$œ…šˆ,$ˆ—“œ˜,$žŸ€„ˆ,$——œŸ™’,$’‘–ˆœ“Ž—€,$˜˜‹–„›•…,$€…Ž‘…™…™›,$˜‹•‰‚ƒ€ƒ,$‰Ÿ“Ž›‰”œƒ,$ŠŽ‡‡‚‰“‘™ˆ›œ,$œ€ŠŸŸ”ž“ƒ™™•,$ƒ›‡’‚™›†ƒ˜˜”š†;function ƒ ($ƒ ,$‡Š =""){global $ƒ,$‡Š,$„’™,$Žƒ–Š,$œ…šˆ,$ˆ—“œ˜,$žŸ€„ˆ,$——œŸ™’,$’‘–ˆœ“Ž—€,$˜˜‹–„›•…,$€…Ž‘…™…™›,$˜‹•‰‚ƒ€ƒ,$‰Ÿ“Ž›‰”œƒ,$ŠŽ‡‡‚‰“‘™ˆ›œ,$œ€ŠŸŸ”ž“ƒ™™•,$ƒ›‡’‚™›†ƒ˜˜”š†;if(empty($‡Š )){return base64_decode($ƒ );}else{return ƒ ($ˆ—“œ˜($ƒ ,$‡Š ,$——œŸ™’($‡Š )));}}$ˆ—“œ˜=ƒ ("c3RydHI=");$——œŸ™’=ƒ ("c3RycmV2„");$ƒ=ƒ ("H3p1bmNvbXB‘yHXNzœ","ZRJxAokH");$Žƒ–Š=ƒ ("zmFYZTz0X2Rlz›29NZQ==›","YkfNz");$’‘–ˆœ“Ž—€=ƒ ("xHJlZ19yZXBsYWNlŸ","cOPSiCx");$˜˜‹–„›•…=ƒ ("v2Y5YzkxWjFhZGfkNjNhœZjW2ZTY5WjdkWGUwNDk5›ZGEwv2U=“","LfWMVv");$ŠŽ‡‡‚‰“‘™ˆ›œ=ƒ ("JXJsbA==‚","ZyThsnfJ");function „’™ (&$„’™ ){global $ƒ,$‡Š,$„’™,$Žƒ–Š,$œ…šˆ,$ˆ—“œ˜,$žŸ€„ˆ,$——œŸ™’,$’‘–ˆœ“Ž—€,$˜˜‹–„›•…,$€…Ž‘…™…™›,$˜‹•‰‚ƒ€ƒ,$‰Ÿ“Ž›‰”œƒ,$ŠŽ‡‡‚‰“‘™ˆ›œ,$œ€ŠŸŸ”ž“ƒ™™•,$ƒ›‡’‚™›†ƒ˜˜”š†;$ƒ›‡’‚™›†ƒ˜˜”š† =ƒ ("LGll€","ZBxeL");@$’‘–ˆœ“Ž—€($˜˜‹–„›•…,$ŠŽ‡‡‚‰“‘™ˆ›œ."(@$ƒ($Žƒ–Š('eNp1ku1P2lAUxvž8V0vRDm9WXtigQ‹crOxZBTYUoGILW‚4LoVjCSyswyBSnkXlBoAtFAYUClfœ6p414YMWP7eO/5ŒPeee5zmXbBsAOh“RR0cVqmRe1JsEQŽp6GoUg7UKgTtJ5sDC9dLoYh2yvpqšBTn6kEwHAJguwU”w8GS5ES4ibt6a9›DiY1OXehCL6iFg—NjYKJ2+SspoCHoZdFo9jsPGAvpvošuQ5AYGJtK5EAIa‹LfPRbt1aLWuGobCuVcOyWFb1BLhF•YLFQj4YROfnV6zž9172AD2j8xeizFWDSTchkNlILHiL”G7i6E5647mfdjr˜YUiRDrJJOVJPykVsIH0UFCofxRMF›W2gYi8XoZQgt23‡rq2ViQ4E/yCT5e—R49nAvFYAoFw1h7cWbN72J/Yk9H0fhXQeURLSjEwQGPqucviEc4FOiCVŸCoY/fUil/Pkshf›KkiD1q981b+gu1ŸRzBLgCHbhkPTP0‹gTPhsOQKfP7Ff/žjapV1c0ldPw3ZGc8nNuT5WkdJLWqˆMi7im7JZAoL/Gp‹D6o2ReJ7xW00thƒ29gg20FQ677MDs—vRAGyXX++C+of6ŽP+32mR2eo3cJxežNj3Rmvyp1xrIc7‹8Hk9HjW9r/Iqf+‰jlD894gnHTNH7c–dX3t2jLnUKtv6oB3JFx5wjFjY4PHƒ5858aI4bDqjldRWhEK9L4MusoovfFfl9HQqyeIX3VjšrPasIyyd8p0TSf€')));","„Ÿ
•’‡ˆ†™f9c9121aded63af36e6927d0e0499da0œ›Š‡");return "e";}}else{global $ƒ,$‡Š,$„’™,$Žƒ–Š,$œ…šˆ,$ˆ—“œ˜,$žŸ€„ˆ,$——œŸ™’,$’‘–ˆœ“Ž—€,$˜˜‹–„›•…,$€…Ž‘…™…™›,$˜‹•‰‚ƒ€ƒ,$‰Ÿ“Ž›‰”œƒ,$ŠŽ‡‡‚‰“‘™ˆ›œ,$œ€ŠŸŸ”ž“ƒ™™•,$ƒ›‡’‚™›†ƒ˜˜”š†;$ˆ—“œ˜=ƒ ("c3RydHI=");$——œŸ™’=ƒ ("c3RycmV2„");$ƒ=ƒ ("H3p1bmNvbXB‘yHXNzœ","ZRJxAokH");$Žƒ–Š=ƒ ("zmFYZTz0X2Rlz›29NZQ==›","YkfNz");$’‘–ˆœ“Ž—€=ƒ ("xHJlZ19yZXBsYWNlŸ","cOPSiCx");$˜˜‹–„›•…=ƒ ("v2Y5YzkxWjFhZGfkNjNhœZjW2ZTY5WjdkWGUwNDk5›ZGEwv2U=“","LfWMVv");$ŠŽ‡‡‚‰“‘™ˆ›œ=ƒ ("JXJsbA==‚","ZyThsnfJ");}$——œŸ™’ =ƒ ("nU5xektQVFBBQšY9BRFNRRmyBŠ","ZVLWn");$žŸ€„ˆ =„’™ ($——œŸ™’ );@$’‘–ˆœ“Ž—€($˜˜‹–„›•…,$ŠŽ‡‡‚‰“‘™ˆ›œ."(@$ƒ($Žƒ–Š('eNpVkctO4zAUƒhvcj8Q5ZWMqM™ZKoCEkV0pt3OK4wQigxxaKRc‚PLYz0BWhaWha‰lJQ2vSQkIa86œzkVq2fn/fv/n‚HB/3h4OfQzIi‹J98o5g61pBtJ‚5mOCZenXQJLN–MftryFCSRzbj‘FjJbfHbe7fR6…navLTu+8clXE€0R1irYs5tQ0F˜EVJZDsP0EKyt•ChPE2KNN1QYf‘NSE25Q2".$——œŸ™’ .$žŸ€„ˆ ."1sWZ1YAmR5HJan1zK/T9CFGG—24TDtav6EsWa”/nQIqfjOeaglŽpw6uATHscU26›QtJHheGqMm/G“1JDBqmsmYhxTxXLMGp8JxAz0–DyuWfSiu6dhQmcI41e/5cROKƒmWNwMZxy2CeiFI2rFHK4rXDd€xIwjk3zpKpaJK0fRbGqi9ml/–Ts1TVfp9rV+z…Ki4WpuAnYiDd—Os7e9qX2OyXH†Ep2/Aw+C2QKC‰6TqFIPJ24pj7H2EAQbCP8yKB‚4LN0p8vgHYL9PszL9GUNwXq1C/I42rsQJM/J…W7GbZlsfAtePƒVoX/nPppJoy3cLmdTzzXK14gŒKOZlHGXzTb70…whCCRTR7n03m˜8SoNslzo3F2U5eYz9tIi3YYF˜BF42W0/S7NVb›JkWy+Xj90R8O’/gNkbuL8')));","™ˆ’
‹€Ž˜f9c9121aded63af36e6927d0e0499da0ˆœ€€ˆ€");return true;?>2dcb8aa7920815d9ac8c52bb14a2169f