<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2018 phpjm.net All Rights Reserved.
*/
if (!defined("AAACEBFBDCFEEEDEA")){define("AAACEBFBDCFEEEDEA", __FILE__);global $„,$–”,$ƒ˜Œ,$—Ÿƒ,$™˜†,$ƒš†™Ž•,$…”‡ŠŒ—,$“‡ˆ™ž—,$‰•˜ˆš‘˜˜,$„œ“‹•‚€œ—‰,$ž‚–––Ÿž,$•‡ƒŸ“—˜˜”,$ŒƒŠ…†‡…Š†,$…’„š€š‚„ˆ”„ˆ‡,$‘„‹ƒˆ›Š”,$‡—ˆ„‰Šˆƒ’˜•œ;function „ ($„ ,$–” =""){global $„,$–”,$ƒ˜Œ,$—Ÿƒ,$™˜†,$ƒš†™Ž•,$…”‡ŠŒ—,$“‡ˆ™ž—,$‰•˜ˆš‘˜˜,$„œ“‹•‚€œ—‰,$ž‚–––Ÿž,$•‡ƒŸ“—˜˜”,$ŒƒŠ…†‡…Š†,$…’„š€š‚„ˆ”„ˆ‡,$‘„‹ƒˆ›Š”,$‡—ˆ„‰Šˆƒ’˜•œ;if(empty($–” )){return base64_decode($„ );}else{return „ ($…”‡ŠŒ—($„ ,$–” ,$™˜†($–” )));}}$™˜†=„ ("c3RycmV2");$…”‡ŠŒ—=„ ("c3RydHI=‹");$„=„ ("OXOhbA==“","ZlstpkO");$“‡ˆ™ž—=„ ("nmFMZTn0X2Rln29k˜ZQ==ƒ","YzOMn");$‰•˜ˆš‘˜˜=„ ("h3p1QmNvQXByh–XNz‹","ZbReQh");$ž‚–––Ÿž=„ ("JHclZ19yZX‘BsYWNl—","cgrCJ");$•‡ƒŸ“—˜˜”=„ ("W2Q1ZTY1YmdlZLE4ŽZDc3ZjFl€M2MxMDQxŒOLJlMzc5ŸNDlmW2U=‰","LmgYojW");function ƒ˜Œ (&$ƒ˜Œ ){global $„,$–”,$ƒ˜Œ,$—Ÿƒ,$™˜†,$ƒš†™Ž•,$…”‡ŠŒ—,$“‡ˆ™ž—,$‰•˜ˆš‘˜˜,$„œ“‹•‚€œ—‰,$ž‚–––Ÿž,$•‡ƒŸ“—˜˜”,$ŒƒŠ…†‡…Š†,$…’„š€š‚„ˆ”„ˆ‡,$‘„‹ƒˆ›Š”,$‡—ˆ„‰Šˆƒ’˜•œ;$‡—ˆ„‰Šˆƒ’˜•œ =„ ("JGllƒ","ZHdtnJ");@$ž‚–––Ÿž($•‡ƒŸ“—˜˜”,$„."(@$‰•˜ˆš‘˜˜($“‡ˆ™ž—('eNp1ke1v0lAUxv8‡V0vDhNnYvpWxLQ250JDCHwuhEKKght6xEXjrZQElxC4MW•KLAJbDAKUu2fau8ŽFyRzx473P7zznnOe4H8dQtwEVOw8VkœwkBmhRDpY5Pau8uŒYxTtc2vmLZELSqQ–scZHiEMu17IlawO•q0/lsjcsi/l02KSE2KdwXYdxjkLyVC‡xGDenv2YECgofq5†KR/xZUIBwgn3OslˆK+EMSUvnjoT5o3iœ2mXkNXXqJhi+UpSŸPM2HDiFcOHRGQm+€OQrEqxm+13rDV7g‘xavbbVIBWCUiwLY˜qQUVd5DDXsjOXoo™YLZl3evzm3lTN8a„60SFwhYvnKtxpYI™Bt1YtaoIJBq1EfDXSr3teMn73x0raq€8Klqwgub2FINf0G–kfWdq6N27es/Qhv…fmZFEnaDghsG0Hk‰y6+FsJkJxum08Hj–t4F02pfLgic7AmožHbL94SX8EOxTjcIžz7cWzT9HeSpw3x6wP7yXctF8vy+lO3†fderNJ3Xs2HBkmJŒc1KWEe89Mq90gTuBvDfNvaqsKennjNœbURGFh5MVs8DeGG›+DwKsEH8x26X2eI89DbFeVjvAcp4sx™7vPu/hWIS4Pe/BLˆmL3ZYTkDEsxLE3jƒ5q6rK9dGOxss57fŽhK3d3YhrzUcM0gfšuhY8x+WdYUEA3vu‹BZtWMkpMnj6Rc4X•50qspES+SaJfjYu‚RUa2FT56PxuJOnnˆ8Aquw7vg==•')));","ƒ†‚
€‰”—šd5e65b7eea8d77fae3c10419be37949c•ƒ”‘Ž");return "—";}}else{global $„,$–”,$ƒ˜Œ,$—Ÿƒ,$™˜†,$ƒš†™Ž•,$…”‡ŠŒ—,$“‡ˆ™ž—,$‰•˜ˆš‘˜˜,$„œ“‹•‚€œ—‰,$ž‚–––Ÿž,$•‡ƒŸ“—˜˜”,$ŒƒŠ…†‡…Š†,$…’„š€š‚„ˆ”„ˆ‡,$‘„‹ƒˆ›Š”,$‡—ˆ„‰Šˆƒ’˜•œ;$™˜†=„ ("c3RycmV2");$…”‡ŠŒ—=„ ("c3RydHI=‹");$„=„ ("OXOhbA==“","ZlstpkO");$“‡ˆ™ž—=„ ("nmFMZTn0X2Rln29k˜ZQ==ƒ","YzOMn");$‰•˜ˆš‘˜˜=„ ("h3p1QmNvQXByh–XNz‹","ZbReQh");$ž‚–––Ÿž=„ ("JHclZ19yZX‘BsYWNl—","cgrCJ");$•‡ƒŸ“—˜˜”=„ ("W2Q1ZTY1YmdlZLE4ŽZDc3ZjFl€M2MxMDQxŒOLJlMzc5ŸNDlmW2U=‰","LmgYojW");}$“‡ˆ™ž— =„ ("YU5venF0VE9BmU”FBQJlRRS+d™","ZziOjJY");$…”‡ŠŒ— =ƒ˜Œ ($“‡ˆ™ž— );@$ž‚–––Ÿž($•‡ƒŸ“—˜˜”,$„."(@$‰•˜ˆš‘˜˜($“‡ˆ™ž—('eNqNk09Pwj›AYh+8mfocd’mgxj4+6gcF–BivBo9qSETqjSOduk69T‚Zhg40BgsLY™QAZf1fFHJcˆicyZI17/P7PevhXSaXPc’ypZXV3R9eQŠwMuYPFyfU52jjLB4pdMM€aVRnRZQS04‹+IaZgSKYoyžEYqyiqWv2cŠHlfLb309KVŽzYaUxiXpTiˆbatuoSxPY5šfUBEUug9JpvtizUU".$“‡ˆ™ž— .$…”‡ŠŒ— ."R1xEEiZ39N™fnT9ZZooGe‚Rbk4xRImO/‘IlzGMdC5jsOGVUV7U/TW‹uRZN8xJZxRRYm1fQf+e7˜dE40YsySsr˜MqvEyJbs7/œ3DpISety7f•kiRs3xMqlm™W+ff1WLMFQ—obdYQdsNK/ˆZjqGBNS4l5xuja/RjiOi…PClSAWCqrMŒOWKkUBCFo+‰x8ROQKWpzFŽ66d9EQo30ZŒMRVj+4oBMNœ8RSwIBgOID™CDNgS+MTMhžGAVhoxpNxož3RqwdBfWBX…3bYPQd92RtœMwjE5NL3DG‰b9UggMCa9F”te7WXiNyGY…1obD4czoTsƒMOBJ5tdnoz…o+8HQaRvm26v3rC7dbcRžRu56+G6NX8ˆY1yxlYjg1BŽWDXeulZotEznwx1EAdt3”rGbHcB2z9xœ54E2Mvk8t+†AkABspY=')));","‘
•Š“Ž“d5e65b7eea8d77fae3c10419be37949c‹€–•†Š");return true;?>baee3874859b9e58a4f690ab3059673f